--===================================================
-- Créé par	: Mathieu Tétreault
-- Créé le	: 2018-01-18
-- Descr.	: Version 1.0 du schéma.
--
-- Les colonnes ID sont les IDENTITY qu'on se génère.
-- Les colonnes StrID sont les IDs que Battlerite génère.
-- Les PK sont initialisées en assumant que PostgreSQL 10.1 est installé.
-- NE CONTIENT PAS LE SCHÉMA POUR LE TELEMETRY.
--===================================================

/*
	Match 
*/

	-- Match
	CREATE TABLE Matches (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		StrID varchar(32), --32 chars selon les exemples
		CreatedAt TIMESTAMPZ, --On veut garder le timezone data.
		Duration INT,
		GameMode varchar(20), --J'ai mis le double des exemples, 10
		PatchVersion varchar(12), --Assez pour major.minor.patch.build?
		ShardID varchar(10), --Aucune idée why 10.
		TitleID varchar(30), --Anyway c'est toujours la mm valeur...?
		ServerType varchar(100), --Pas d'exemples!
		RankingType varchar(100), --Pas d'exemples!
		StatsMapID varchar(32), --32 selon l'exemple
		StatsMatchType varchar(20)
	)

/*
	Rosters Data
*/

	-- MatchRoster
	CREATE TABLE MatchRoster (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		StrID varchar(40), --36 chars selon les exemples
		MatchID INT REFERENCES Matches, --Par défaut, ID
		RosterType varchar(100), --Pas d'exemple!
		Won boolean,
		ShardID varchar(10) --Aucune idée why 10.
	)

	--RosterStatType
	CREATE TABLE RosterStatType (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		StatName varchar(50)
	)

	--MasterRosterStats
	CREATE TABLE MatchRosterStats (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		MatchRosterID INT REFERENCES MatchRoster,
		RosterStatTypeID INT REFERENCES RosterStatType,
		StatValue varchar(50)
	)



/*
	Rounds
*/

	--MatchRound
	CREATE TABLE MatchRound (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		StrID varchar(40), --36 chars selon les exemples
		MatchID INT REFERENCES [Match], --Par défaut, ID
		RoundIndex bigint,
		Duration bigint
	)

	--RoundStatType
	CREATE TABLE RoundStatType (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		StatName varchar(50)
	)
	
	--MatchRoundStats
	CREATE TABLE MatchRoundStats (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		MatchRoundID INT REFERENCES MatchRound,
		RoundStatTypeID INT REFERENCES RoundStatType,
		StatValue varchar(50)
	)

/*
	Player
*/

	--PlayerStatType
	CREATE TABLE PlayerStatType (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		StatName varchar(50)
	)

	--Player
	CREATE TABLE Player (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		StrID varchar(40), --36 chars selon les exemples
		Name varchar(100),
		PatchVersion varchar(12), --Assez pour major.minor.patch.build?
		ShardID varchar(10), --Aucune idée why 10.
		TitleID varchar(30) --Anyway c'est toujours la mm valeur...?
	)

	--PlayerStats
	CREATE TABLE PlayerStats (
		PlayerID INT REFERENCES Player,
		StatTypeID INT REFERENCES PlayerStatType,
		StatValue varchar(50)
	)

/*
	Team
*/

	--Team
	CREATE TABLE Team (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		StrID varchar(40), --36 chars selon les exemples
		Name varchar(50),
		TeamID INT,
		Division INT,
		DivisionRating INT,
		League INT,
		Losses INT,
		PlacementGamesLeft INT,
		TopDivision INT,
		TopDivisionRating INT,
		TopLeague INT,
		Wins INT,
		TitleID varchar(30) --Anyway c'est toujours la mm valeur...?
	)
	
	--TeamPlayer
	CREATE TABLE TeamPlayer (
		TeamID INT REFERENCES Team,
		PlayerID INT REFERENCES Player
	)
	
	--MatchRosterTeam
	CREATE TABLE MatchRosterTeam (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		MatchRosterID INT REFERENCES MatchRoster,
		Name varchar(50),
		TeamID INT REFERENCES Team,
		TitleID varchar(30), --Anyway c'est toujours la mm valeur...?
		ShardID varchar(10) --Aucune idée why 10.
	)
	
/*
	Participants
*/

	--ParticipantStatType
	CREATE TABLE ParticipantStatType (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		StatName varchar(50)
	)
	
	--MatchRosterParticipants
	CREATE TABLE MatchRosterParticipants (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		StrID varchar(40), --36 chars selon les exemples
		Actor varchar(50),
		MatchRosterID INT REFERENCES MatchRoster,
		PlayerID INT REFERENCES Player
		PlayerType varchar(50)
	)
		
	--ParticipantStats
	CREATE TABLE ParticipantStats (
		ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
		ParticipantID INT REFERENCES MatchRosterParticipants,
		ParticipantStatTypeID INT REFERENCES ParticipantStatType,
		StatValue varchar(50)
	)