version: '3'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
  crawler:
    build:
      context: ./crawler
    env_file:
      - dot.env
    volumes:
      - ./crawler/:/app/
  edge:
    build:
      context: ./
      dockerfile: ./edge/Dockerfile-dev
    ports:
      - "80:80"
    volumes:
      - ./web/dst/:/app/dst/
  api:
    build:
      context: ./api
    env_file:
      - dot.env
    volumes:
      - ./api/src/:/app/src/
      - ./api/app.js:/app/app.js
  web:
    build:
      context: ./web
    env_file:
      - dot.env
    volumes:
      - ./web/:/app/

volumes:
  db-data:
